# Generated by Django 3.2.9 on 2021-11-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageeditmodel',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
