# Generated by Django 3.2.9 on 2021-11-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_imageeditmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageeditmodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
