# Generated by Django 3.2.9 on 2021-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Getviptools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_views_vip_tools', 'Can View Vip Tools')],
            },
        ),
    ]
